name: Build and Sign APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      #Decode and save JKS file from Base64
      - name: Decode and save JKS file
        env:
          JKS_BASE64: ${{ secrets.JKS_BASE64 }}
        run: |
          echo "$JKS_BASE64" | base64 --decode > app/my-release-key.jks

      #Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      #Clean the build
      - name: Clean the build
        run: ./gradlew clean

      #Build APK with Gradle (signing via command-line parameters)
      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: my-release-key.jks  # Keystore file path
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # Step 7: Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk